python:
  - "3.6"

# command to install dependencies
install:
  - "pip install pipenv"
  - "pipenv install -d"

before_script: "pipenv run flake8 aurora_webapp/"

# command to run tests
script: "pipenv run nosetests"
